export const LOAD_MORE = "LOAD_MORE"
export const FETCH_GIFS = "FETCH_GIFS"
export const FETCH_START = "FETCH_START"
export const FETCH_STOP = "FETCH_STOP"
export const CLEAR_SEARCH = "CLEAR_SEARCH"
export const SEARCH_GIFS = "SEARCH_GIFS"
export const SAVE_GIF = "SAVE_GIF"
export const FETCH_FAVORITE_GIFS = "FETCH_FAVORITE_GIFS"